- name: Lancer le conteneur de la base de donnees
  docker_container:
    name: my_postgres
    image: melisadou/tp-devops-database
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: my_network
    published_ports:
      - "5432:5432"
